name: Geo-Location-Backend-Deployment

on:
  push:
    branches: ["main"]

jobs:
  Geo-Location-Backend-Deployment:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: git pull on server
        working-directory: /home/master/applications/cxxsauvesn/public_html
        run: git pull
      - name: Install Dependencies
        working-directory: /home/master/applications/cxxsauvesn/public_html
        run: npm install
      - name: Restart the server
        working-directory: /home/master/applications/cxxsauvesn/public_html
        run: pm2 restart app.js
